# hugo.toml

# Basic configuration
baseURL = 'https://s4dr0t1.github.io'
languageCode = 'en-us'
title = 's4dr0t1'
theme = "Papermod"

# Build options
buildDrafts = false
buildExpired = false
buildFuture = false

# Miscellaneous
enableGitInfo = true
enableEmoji = true
