# Homepage visible information
[homeInfoParams]
Title = "[~]$ whoami?"
Content = """
Hi, I'm Rohit (@s4dr0t1). I'm a budding security researcher with interests in blue teaming, reverse engineering, binary exploitation, wireless and network security.

[ [About](/about) ] [ [Blog](/archives) ] [ [Contact](/contact) ] [ [PGP Key](https://keys.openpgp.org/vks/v1/by-fingerprint/B93E806F0DA033094B801EA69FA224D074C72FD9) ]
"""

[[socialIcons]]
name = "github"
url = "https://github.com/s4dr0t1"

[[socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/in/rohitdhill/"

[[socialIcons]]
name = "More information"
url = "/contact"
env = 'production'        # Enable OpenGraph protocol


# Other configurable stuff
#images = "/link"
author = "s4dr0t1"
DateFormat = "January 2, 2006"
defaultTheme = "light"
DisableThemeToggle = false
ShowReadingTime = false
ShowShareButtons = false
disableAnchoredHeadings = false
ShowPostNavLinks = false
ShowBreadCrumbs = false
ShowCodeCopyButtons = true
ShowWordCount = true
ShowRssButtonInSectionTermList = true
UseHugoToc = true
disableSpecial1stPost = false
disableScrollToTop = false
comments = false
hidemeta = false
hideSummary = false
showtoc = true
tocopen = false


# Explore this
#[cover]
#hidden = true
#hiddenInList = true
#hiddenInSingle = true


#[assets]
#favicon = "<link / abs url>"
#favicon16x16 = "<link / abs url>"
#favicon32x32 = "<link / abs url>"
#apple_touch_icon = "<link / abs url>"
#safari_pinned_tab = "<link / abs url>"


# SEO shit
title = "A security research blog - by Rohit Dhill (@s4dr0t1)"

description = "A security research blog - by Rohit Dhill (@s4dr0t1), specializing in blue teaming, reverse engineering, system internals, and trusted computing stuff. Featuring technical write-ups, security research, and blue team insights."

keywords = [
	"Cybersecurity",
	"Blog",
	"Portfolio",
	"s4dr0t1",
	"Rohit Dhill",
	"Security Research",
	"Reverse engineering",
	"Low level programming",
	"Detection Engineering",
	"Blue Teaming",
	"Cryptography",
	"Systems programming",
	"OS internals",
	"Networking",
	"Hypervisors",
	"Privacy",
	"Trusted Computing",
]
