# SEO information
keywords = [
	"Cybersecurity",
	"Blog",
	"Portfolio"
]

# Appearance
env = 'production' 	# Enable OpenGraph protocol
#images = "/link"

defaultTheme = 'auto'
DisableThemeToggle = false

ShowReadingTime = true
ShowShareButtons = false
ShowPostNavLinks = true
ShowBreadCrumbs = false
ShowCodeCopyButtons = true
ShowWordCount = true
ShowRssButtonInSectionTermList = true
UseHugoToc = true
disableSpecial1stPost = false
disableScrollToTop = false
comments = false
hidemeta = false
hideSummary = false
showtoc = true
tocopen = false

[homeInfoParams]
Title = "[~]$ whoami?"
Content = """
Hi, I'm Rohit (@s4dr0t1). I'm a budding security researcher with interests in reverse engineering, binary exploitation, wireless and network security.

[ [About](/about) ] [ [Blog](/archives) ] [ [Contact](/contact) ] [ [PGP Key](https://keys.openpgp.org/vks/v1/by-fingerprint/CAAF47E471E769D34DC3912F950AD2384C65B8B3) ]
"""

[[socialIcons]]
name = "github"
url = "https://github.com/s4dr0t1"

[[socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/in/rohitdhill/"

[[socialIcons]]
name = "More information"
url = "/contact"
